# Generated by Django 5.2.5 on 2026-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('ave_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComun', models.CharField(max_length=60)),
                ('nombreCientifico', models.CharField(max_length=60)),
                ('familia', models.CharField(max_length=40)),
                ('especie', models.CharField(max_length=40)),
                ('audio', models.FileField(upload_to='audios_ave/')),
            ],
        ),
    ]
