# Generated by Django 5.2.5 on 2026-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colbirdApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ave',
            name='imagen',
            field=models.FileField(default='', upload_to='imgs_ave/'),
        ),
    ]
