# Generated by Django 5.2.8 on 2026-06-16 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colbirdApp', '0002_ave_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colbirdApp.ave')),
            ],
        ),
    ]
